[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x65737e"
blue = "0xa7adba"
cyan = "0xab7967"
green = "0x343d46"
magenta = "0xdfe1e8"
red = "0xd08770"
white = "0xeff1f5"
yellow = "0x4f5b66"

[colors.cursor]
cursor = "0xc0c5ce"
text = "0x2b303b"

[colors.normal]
black = "0x2b303b"
blue = "0x8fa1b3"
cyan = "0x96b5b4"
green = "0xa3be8c"
magenta = "0xb48ead"
red = "0xbf616a"
white = "0xc0c5ce"
yellow = "0xebcb8b"

[colors.primary]
background = "0x2b303b"
foreground = "0xc0c5ce"

[font]
size = 16.0

[font.normal]
family = "Noto Sans Mono"

[scrolling]
history = 0

[window]
decorations = "none"
startup_mode = "Maximized"
