#!/bin/bash
NO_COLOR="\e[0m"
RED="\e[1;31m"
GREY="\e[1;36m"
GREEN="\e[1;32m"
BLUE="\e[1;34m"
YELLOW="\e[0;33m"
BLACK="\e[0;30m"
PURPLE="\e[1;35m"

ps1_git() {
    local branch
    local status
    local color
    local numChanged
    local numUntracked
    local changed
    local untracked
    local stashed

    branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null)
    if [ "$branch" ]; then
        status=$(git status --short)

        color=$GREEN
        numChanged=$(grep '^.M' <<< "$status" | wc -l | awk '{print $1}')
        numUntracked=$(grep '^??' <<< "$status" | wc -l | awk '{print $1}')
        numStashed=$(git stash list | grep "on $branch" | wc -l | awk '{print $1}')

        [ $numChanged -gt 0 ] && {
            changed=" ~${numChanged}"
            color=$PURPLE
        }
        [ $numUntracked -gt 0 ] && {
            untracked=" +$numUntracked"
        }
        [ $numStashed -gt 0 ] && {
            stashed=" {$numStashed}"
        }
        echo " \[$BLACK\]\[$color\]$branch$changed$untracked$stashed"
    fi
}

ps1_update() {
    local env
    local git

    [[ "$VIRTUAL_ENV" ]] && {
        env="($(basename $VIRTUAL_ENV)) "
    }

    git=$(ps1_git)

    PS1="$env\[$BLUE\]$PWD \[$NO_COLOR\]on\[$GREY\] $(hostname)"
    PS1="${PS1}${git}\n  \[$BLUE\]\\\$ \[$NO_COLOR\]"
}

_update_ps1() {
    PS1="$(powerline-shell.py --cwd-mode plain --mode flat $?)"
}

if [ "$TERM" != "linux" ]; then
    PROMPT_COMMAND=_update_ps1
fi
